import type { Lang } from "./types";

export const STRINGS = {
  zh: {
    appSubtitle: "Notion 导入 memos 控制台",
    configTitle: "配置",
    endpointLabel: "memos 端点",
    memosTokenLabel: "memos Token",
    notionTokenLabel: "Notion Token",
    timeSourceLabel: "时间来源",
    propertyLabel: "日期属性名",
    strategyLabel: "重复导入",
    visibilityLabel: "导入可见性",
    visibilityPrivate: "私有",
    visibilityProtected: "登录可见",
    visibilityPublic: "公开",
    workersLabel: "并发",
    saveBtn: "保存",
    verifyBtn: "校验",
    verifying: "校验中...",
    savedToast: "配置已保存到本地浏览器",
    statusTitle: "连接状态",
    statusIdle: "尚未校验",
    statusChecking: "校验中",
    statusOk: "已连接",
    statusError: "连接失败",
    jobsTitle: "导入任务",
    jobsEmpty: "暂无导入任务",
    jobDone: "已完成",
    jobFailed: "失败",
    jobRunning: "导入中",
    jobCanceled: "已取消",
    jobPending: "等待中",
    docsTitle: "文档",
    searchPlaceholder: "搜索文档标题...",
    loadLimitLabel: "加载数量",
    loadBtn: "加载 Notion 文档",
    loadingBtn: "加载中...",
    moreDocuments: "仍有更多文档",
    invalidDocumentLimit: "加载数量必须是 1 到 1000 之间的整数",
    importBtn: "导入到 memos",
    importingBtn: "导入中...",
    selected: "已选",
    listEmptyTitle: "还没有文档",
    listEmptyDesc: "点击加载拉取页面与数据库列表",
    previewEmptyTitle: "选择文档查看预览",
    previewEmptyDesc: "Markdown 内容与转换警告会显示在这里",
    warningsLabel: "转换警告",
    resultTitle: "任务明细",
    unlockTitle: "访问认证",
    unlockBtn: "解锁",
    passwordLabel: "访问密码",
    openBtn: "详情",
    cancelBtn: "取消",
    resumeBtn: "恢复",
    retryBtn: "重试失败项",
    docTypeDatabase: "数据库",
    docTypePage: "页面",
    noPreviewForDatabase: "数据库",
    overLimit: "内容超过 memos 限制",
    maskedToken: "已保存",
  },
  en: {
    appSubtitle: "Notion to memos import console",
    configTitle: "Config",
    endpointLabel: "memos endpoint",
    memosTokenLabel: "memos token",
    notionTokenLabel: "Notion token",
    timeSourceLabel: "Time source",
    propertyLabel: "Date property",
    strategyLabel: "Duplicate policy",
    visibilityLabel: "Import visibility",
    visibilityPrivate: "Private",
    visibilityProtected: "Signed-in",
    visibilityPublic: "Public",
    workersLabel: "Workers",
    saveBtn: "Save",
    verifyBtn: "Verify",
    verifying: "Verifying...",
    savedToast: "Config saved in this browser",
    statusTitle: "Connection status",
    statusIdle: "Not verified",
    statusChecking: "Checking",
    statusOk: "Connected",
    statusError: "Connection failed",
    jobsTitle: "Import jobs",
    jobsEmpty: "No import jobs yet",
    jobDone: "Done",
    jobFailed: "Failed",
    jobRunning: "Running",
    jobCanceled: "Canceled",
    jobPending: "Pending",
    docsTitle: "Documents",
    searchPlaceholder: "Search document titles...",
    loadLimitLabel: "Load count",
    loadBtn: "Load Notion docs",
    loadingBtn: "Loading...",
    moreDocuments: "More documents available",
    invalidDocumentLimit: "Load count must be an integer from 1 to 1000",
    importBtn: "Import to memos",
    importingBtn: "Importing...",
    selected: "Selected",
    listEmptyTitle: "No documents yet",
    listEmptyDesc: "Load pages and databases",
    previewEmptyTitle: "Select a document to preview",
    previewEmptyDesc: "Markdown and conversion warnings appear here",
    warningsLabel: "Conversion warnings",
    resultTitle: "Job detail",
    unlockTitle: "Access",
    unlockBtn: "Unlock",
    passwordLabel: "Access password",
    openBtn: "Open",
    cancelBtn: "Cancel",
    resumeBtn: "Resume",
    retryBtn: "Retry failed",
    docTypeDatabase: "database",
    docTypePage: "page",
    noPreviewForDatabase: "database",
    overLimit: "Content exceeds memos limit",
    maskedToken: "saved",
  },
};

export type Strings = (typeof STRINGS)[Lang];
